### ISSUE TITLE
Test scripts didn't correctly detect 'pg_dump' being invoked as 'pg_dump .... -d <database>'

### ISSUE THREAD

**Issue by ehuelsmann** [ledgersmb/PGObject-Util-DBAdmin#11]
Which is a problem, because `-d` is not a supported option.

**Comment by nick-prater** [comment]
While `-d` isn't officially supported, I get identical output and no errors or warnings whether I use `pg_dump .... -d <database>` or `pg_dump .... <database>`.

I've tested with `pg_dump (PostgreSQL) 9.6.6` and `pg_dump (PostgreSQL) 9.5.11`.

Did you see a problem when the -d option was used?

**Comment by nick-prater** [comment]
I believe this is dependent on the pg_dump version in use.

We can't feasibly test against all possible pg_dump versions in a perl module test. So I propose closing this bug.

The rogue `-d` option has been removed, and didn't cause any warning or error on the systems I've tested. The user can run module tests against their own postgresql/pg_dump installation, which tests a backup-restore cycle.
