### ISSUE TITLE
Backup methods silently fail on some errors

### ISSUE THREAD

**Issue by nick-prater** [ledgersmb/PGObject-Util-DBAdmin#12]
`backup`, `backup_globals`, `restore` and `drop` methods only fail on ERROR or FATAL warning messages. They do not indicate failure for other error conditions reported by the shell, for example 'permission denied' or 'no such file'.

This is particularly dangerous with the backup methods, where success is reported to the caller even when the backup has failed an no backup file has been created.

**Comment by nick-prater** [comment]
I've just encountered another situation where this causes backups to silently fail: `pg_dump: aborting because of server version mismatch` isn't trapped - backup methods still indicate success. We need to check the exit code, not just stderr output.

**Comment by ehuelsmann** [comment]
@nick-prater I'm thinking that checking for `ERROR` or `FATAL` isn't particularly helpful: what if there's legitimate output which contains either keyword?

**Comment by nick-prater** [comment]
You're right - there could be legitimate output that contains either keyword. Is checking the exit code alone (which we didn't before starting to address this issue) sufficient?

**Comment by ehuelsmann** [comment]
From the `psql` docs:

> Exit Status
>
> psql returns 0 to the shell if it finished normally, 1 if a fatal error of its own occurs (e.g. out of memory, file not found), 2 if the connection to the server went bad and the session was not interactive, and 3 if an error occurred in a script and the variable ON_ERROR_STOP was set.

In other words, I think checking the exit status is enough, if we provide the following additional command line argument:

`--set=ON_ERROR_STOP=on`

as I think to conclude from https://www.postgresql.org/docs/9.2/static/app-psql.html

**Comment by nick-prater** [comment]
That's good research for psql - thanks.

What about pg_dump?
https://www.postgresql.org/docs/current/static/app-pgdump.html
makes no mention of exit status, but says:
> While running pg_dump, one should examine the output for any warnings (printed on standard error)

For pg_restore I propose adding the `--exit-on-error` flag. See:
https://www.postgresql.org/docs/10/static/app-pgrestore.html

**Comment by nick-prater** [comment]
Addressed by PR #28
