### ISSUE TITLE
Errors on checking temporary file existence

### ISSUE THREAD

**Issue by ylavoie** [ledgersmb/PGObject-Util-DBAdmin#38]
Migration fails with `-e on closed filehandle $fh at /usr/local/share/perl/5.18.2/PGObject/Util/DBAdmin.pm line 361.`
`File::Temp` should react properly on the `-e` file existence check but seems to be failing instead.
`run_file` is called with arguments shown below:
```
2018/05/17 01:53:46 - WARN - PGObject::Util::DBAdmin::run_file /usr/local/share/perl/5.18.2/PGObject/Util/DBAdmin.pm (361) -- {
    errlog       "/tmp/dblog_2018-05-17T015342_32_stderr",
    file         File::Temp  {
        Parents       IO::Handle, IO::Seekable
        Linear @ISA   File::Temp, IO::Handle, Exporter, IO::Seekable
        internals: *File::Temp::$fh  (layers: )
    },
    stdout_log   "/tmp/dblog_2018-05-17T015342_32_stdout"
} at /usr/local/share/perl/5.18.2/PGObject/Util/DBAdmin.pm line 361.

```

**Comment by nick-prater** [comment]
@ylavoie could you please provide steps to replicate this problem. I'm trying to create a test, but so far have been unable to reproduce. Many thanks.

**Comment by nick-prater** [comment]
This is a bug is lsmb, not DBAdmin. See https://github.com/ledgersmb/LedgerSMB/pull/3622
