### ISSUE TITLE
Spelling error in lib/PGObject/Util/DBAdmin.pm

### ISSUE THREAD

**Issue by jame** [ledgersmb/PGObject-Util-DBAdmin#39]
While working on the Debian packaging for the module, the following spelling errors were found; two instances of the word  parameter instead being spelled as  paramter, Also, see attached patch: 
[SpellingErrors.txt](https://github.com/ledgersmb/PGObject-Util-DBAdmin/files/2073283/SpellingErrors.txt)

**Comment by ehuelsmann** [comment]
Resolved in adb838749b4e530148cfa0c01d3c1da51892723e
